### ISSUE TITLE
Loaded packages information messed up by more complex shell

### ISSUE THREAD

**Issue by knedlsepp** [haslersn/any-nix-shell#1]
When I run:
```
nix-shell -p "(python.withPackages(ps: with ps; [numpy pint pandas]))"
```
The terminal reads: "[numpy pandas])) pint ps; (python.withPackages(ps: with"

**Comment by haslersn** [comment]
Fixing this is unfortunately not straightforward because environment variables can't hold arrays.

By the way: Did you try [lorri](https://github.com/target/lorri)? It's much better than any-nix-shell.
