### ISSUE TITLE
No longer works for fish with 'nix run'

### ISSUE THREAD

**Issue by spacekookie** [haslersn/any-nix-shell#10]
With the last update `nix run -f '<nixpkgs>' hello` will no longer use the fish shell, but rather default to bash.

**Comment by haslersn** [comment]
Update of `nix` or update of `any-nix-shell`? Which version of Nix are you using?

**Comment by BuriedInTheGround** [comment]
Unfortunately, it seems that in `nix run` they actually hardcoded `bash` (see [here](https://github.com/NixOS/nix/blob/90b2dd570cbd8313a8cf45b3cf66ddef2bb06e07/src/nix/run.cc#L65)).

**Comment by haslersn** [comment]
@spacekookie Does #13 fix this issue for you?

**Comment by drupol** [comment]
@spacekookie We are waiting for feedback in order to merge #13, could you confirm it works?

**Comment by spacekookie** [comment]
Hey! Sorry for the long delay in response. #13 does indeed fix my problem :) Thank you
