### ISSUE TITLE
`nix develop` (flake) support ? 

### ISSUE THREAD

**Issue by drupol** [haslersn/any-nix-shell#12]
Hello,

I'm switching my projects and use more and more flakes.
When I do `nix develop`, it starts a bash shell instead of continue to use my current shell on fish.

Do you think it's possible to use `any-nix-shell` so it works with `nix develop` ?

**Comment by sbourdeauducq** [comment]
I guess this line needs to be modified: https://github.com/haslersn/any-nix-shell/blob/master/bin/any-nix-shell#L15

**Comment by sbourdeauducq** [comment]
This fixes it for fish:
```

**Comment by drupol** [comment]
How about making a pull request ?

**Comment by sbourdeauducq** [comment]
``.any-nix-wrapper`` would also need an update, otherwise it seems ``nix develop`` gets aliased to ``nix shell``.

**Comment by haslersn** [comment]
@sbourdeauducq is right. I'm working on it.

**Comment by haslersn** [comment]
`nix develop` and the old `nix run` (Nix 2.0 - 2.3) have very different command line options. Therefore, supporting `nix develop` would require some larger changes.

@drupol It seems in Nix 2.4 they reintroduced `nix shell`, which uses the user's default shell, so any-nix-shell is not required. Can you use `nix shell` instead of `nix develop`? It seems the Nix developers deliberately made it so that `nix develop` uses bash, in order to make debugging builds possible.

**Comment by sbourdeauducq** [comment]
> Can you use `nix shell` instead of `nix develop`?

Unfortunately ``nix shell`` means using ``pkgs.buildEnv`` and not ``pkgs.mkShell``. This means you cannot set environment variables in the shell from the flake, and also it appears that some programs such as ``llvm-config`` (or build tools using it) misbehave in the forest of symlinks created by ``pkgs.buildEnv``.

> It seems the Nix developers deliberately made it so that `nix develop` uses bash, in order to make debugging builds possible.

Ah yes - that would make sense...

**Comment by drupol** [comment]
On my side, I found a workaround: `nix develop --command fish`

**Comment by evanrelf** [comment]
FYI [`nix-your-shell`](https://github.com/MercuryTechnologies/nix-your-shell) has support for `nix-develop`.

**Comment by drupol** [comment]
Unable to build it, doesn't look like the maintainer is taking care of the it anymore.

**Comment by evanrelf** [comment]
You can get the latest release from Nixpkgs:

```ShellSession
λ nix build nixpkgs#nix-your-shell

λ ./result/bin/nix-your-shell --version
nix-your-shell 1.1.1
```
