### ISSUE TITLE
nix shell does not work with fish

### ISSUE THREAD

**Issue by aadibajpai** [haslersn/any-nix-shell#14]
I followed the installation instructions from the readme. However it does not seem to work:
![image](https://user-images.githubusercontent.com/27063113/147263794-73c7bb23-8320-4832-99ef-7cf1330e539f.png)
I am on macOS, with fish version 3.3.1 and nix 2.4.

**Comment by haslersn** [comment]
This issue cannot happen since #13 got merged.
