### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by thiagokokada** [haslersn/any-nix-shell#35]
As asked in https://github.com/NixOS/nixpkgs/pull/327866#issuecomment-2232976263, we need a new release to fix the `nix --version` >= 2.4 issues.

Also, before a new release it would be great to get https://github.com/haslersn/any-nix-shell/pull/34 merged. While it is not necessary to do so (since the code works correctly without it), having support for `nix develop` is half of the reason you would want `any-nix-shell` when using Flakes.

**Comment by thiagokokada** [comment]
CC @haslersn.

**Comment by AndersonTorres** [comment]
https://github.com/haslersn/any-nix-shell/issues/12#issuecomment-986031541

**Comment by haslersn** [comment]
@thiagokokada does https://github.com/haslersn/any-nix-shell/releases/tag/v2.0.0 work for you?

**Comment by thiagokokada** [comment]
> @thiagokokada does https://github.com/haslersn/any-nix-shell/releases/tag/v2.0.0 work for you?

Nice, I will update the PR in nixpkgs soon.
