### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by veehaitch** [haslersn/any-nix-shell#7]
I'd like to update `any-nix-shell` in `nixpkgs` to bring #6 to upstream. Could you please create a new release? Thanks!

**Comment by haslersn** [comment]
https://github.com/haslersn/any-nix-shell/releases/tag/v1.2.0

**Comment by veehaitch** [comment]
Thanks for the quick response! https://github.com/NixOS/nixpkgs/pull/108011
