### ISSUE TITLE
Unload option?

### ISSUE THREAD

**Issue by KenMacD** [haslersn/any-nix-shell#9]
Is there any way to 'undo' these changes in a `shell.nix`? If not could there be?

I know I could just unload the `nix-shell` function or pass `--command`, the problem is that I'm using direnv which starts the shell automatically. Occasionally I'd rather have a `shell.nix` using bash. It'd be nice if there was something I could include in the shell definition that would run bash.

**Comment by haslersn** [comment]
There are workarounds to skip any-nix-shell:

- Run `env nix-shell`
- Or run `nix-shell --command return`

direnv can probably be instructed to use the latter workaround by putting the following in `.envrc`:

```
use nix --command return
```

Though I didn't test this.
